(function(g){'use strict';
const D=g.CAMPUS_DATA,C=g.CAMPUS_CONTENT,U=g.CampusUI,M=g.CampusMath,V=g.CampusViews;
function initialState(){return{subsystem:0,dataTab:'official',indicator:'AREA_PC',emIndicator:'X14',release:2025,horizon:3,model:'RT',kappa:5,floorFactor:1,caseId:'history',stage:0,cycleSummary:false,programTab:'compose',goal:'M06',selectedMeasures:['M05','M06'],existing:{history:false,knowledge:true,supply:true,norm:true},sameRoom:true,changedMeasures:['M05'],externalChange:'',registryComplete:true,calendar:{start1:1,duration1:5,load1:1,start2:2,duration2:5,load2:1,capacity:1},p:.4,criterion:'expected',limits:{cash:180,labor:80,hours:48,repeat:.10},sensitivity:.8,specificity:.8,infoPrice:2,infoLabor:2,infoDelay:0,pLow:.2,pHigh:.5,trace:'normal',mutation:-1,traceStep:-1,permutationResult:null,graphTab:'source',nodeGroup:'all',graph:{w1:.3,w2:.4,feedback:-.1,lag1:0,lag2:1,source:0,step:0},expertMedian:18,expertVariance:.01,lambda:.35,mixScale:2.5,compatible:true,mixThreshold:16,decisionThreshold:.5,gapYear:'2024',gap1:-2,gap2:2,sumStart:1,sumEnd:3,matrix:{a:2,b:1,c:1,d:3,x:1,y:2},formulaGroup:'all',formulaSearch:'',glossarySearch:'',tableId:82,answers:{},feedback:{},assisted:{},mastery:{}};}
let S=initialState();
const titles={home:'Обзор кампуса',read:'Понять исследование',basics:'Математика с нуля',data:'Данные и их смысл',forecast:'Прогнозные модели',cycle:'Путь решения',program:'Программа мер',measure:'Паспорт меры',economics:'Выбор исполнения',information:'Ценность информации',process:'Проверка работ',graph:'Связи и динамика',mixture:'Экспертное уточнение',evaluation:'Оценка результата',formulas:'Формулы',glossary:'Глоссарий',tables:'Исходные таблицы',sources:'Основания и ограничения',session:'Текущий разбор'};
const navGroups=[['НАЧАТЬ',[['home','Кампус как система','home'],['read','Понять исследование','book'],['basics','Математика с нуля','bulb'],['cycle','Путь решения','arrow']]],['ДАННЫЕ И МОДЕЛИ',[['data','Данные кампуса','grid'],['forecast','Прогнозы','chart'],['graph','Связи и задержки','network'],['mixture','Экспертное уточнение','beaker']]],['ПРИНЯТЬ И ПРОВЕРИТЬ',[['program','Программа мер','layers'],['economics','Экономический выбор','target'],['information','Ценность информации','bulb'],['process','Проверка исполнения','shield'],['evaluation','Оценка результата','chart']]],['СПРАВОЧНИК',[['formulas','Формулы','grid'],['glossary','Понятия','book'],['tables','Таблицы','grid'],['sources','Источники и границы','info']]]];
let route={page:'home',id:null},simple=true,lastRenderedRoute='';
const questions={};for(const ch of C.chapters)questions['chapter-'+ch.id]=ch.question;for(const l of C.basics)questions['basic-'+l.id]=l.question;for(const c of C.cases)for(const q of c.questions)questions['case-'+q.id]=q;
function parseRoute(){const raw=location.hash.replace(/^#\/?/,'').split('?')[0];let parts=raw.split('/');try{return{page:parts[0]||'home',id:parts[1]?decodeURIComponent(parts.slice(1).join('/')):null};}catch(e){return{page:'not-found',id:null};}}
function announce(s){document.getElementById('announcer').textContent=s;}
function nav(){document.getElementById('sidebar').innerHTML=`<a href="#/home" class="brand"><span class="brand-mark"><svg width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M3 20V9l9-6 9 6v11M1 20h22M8 20v-8h8v8"/></svg></span><span><b>Кампус</b><small>ЛАБОРАТОРИЯ УПРАВЛЕНИЯ</small></span></a>${navGroups.map(([label,links])=>`<nav class="nav-group" aria-label="${label}"><div class="nav-label">${label}</div>${links.map(([p,t,ic])=>`<a class="nav-link ${route.page===p||p==='program'&&route.page==='measure'?'active':''}" href="#/${p}" ${route.page===p?'aria-current="page"':''}>${g.icon(ic)}<span>${t}</span></a>`).join('')}</nav>`).join('')}<div class="sidebar-bottom"><a href="#/session" class="inline-link" style="color:#d0e7b1">Мой разбор этого сеанса</a><p style="margin-top:12px">Данные не становятся фактами<br>только после вычисления.</p></div>`;}
function render(preserve=false){const routeKey=route.page+'/'+(route.id||''),sameRoute=routeKey===lastRenderedRoute,opened=sameRoute?Array.from(document.querySelectorAll('#main details')).map((d,i)=>({i,title:d.querySelector('summary')?.textContent,open:d.open})).filter(x=>x.open):[];let key=null,action=null,start=null,end=null;if(preserve){const a=document.activeElement;if(a){key=a.dataset.bind;action=a.dataset.focusKey;try{start=a.selectionStart;end=a.selectionEnd;}catch(e){}}}document.body.classList.toggle('simple',simple);document.title=(titles[route.page]||'Кампус')+' · Кампус';document.getElementById('breadcrumb').textContent='Лаборатория управления / '+(titles[route.page]||'Раздел');nav();try{document.getElementById('main').innerHTML=(V[route.page]||V.notFound)(S,route.id);}catch(e){console.error(e);document.getElementById('main').innerHTML=U.intro('Не удалось выполнить этот расчёт','Вернитесь к исходным условиям. Введённые данные не отправлялись на сервер.')+U.note(U.esc(e.message),'error')+U.btn('Сбросить сеанс','reset-session','','primary');}
lastRenderedRoute=routeKey;const details=Array.from(document.querySelectorAll('#main details'));for(const o of opened){const d=details[o.i];if(d&&d.querySelector('summary')?.textContent===o.title)d.open=true;}
if(key){const a=document.querySelector(`[data-bind="${CSS.escape(key)}"]`);if(a){a.focus({preventScroll:true});if(start!==null)try{a.setSelectionRange(start,end);}catch(e){}}}else if(action){document.querySelector(`[data-focus-key="${CSS.escape(action)}"]`)?.focus({preventScroll:true});}}
function onRoute(){route=parseRoute();if(route.page==='data'&&['match','scenario','official'].includes(route.id))S.dataTab=route.id;if(route.page==='program'&&['compose','reconfigure','calendar'].includes(route.id))S.programTab=route.id;if(route.page==='graph'&&['source','play','stability'].includes(route.id))S.graphTab=route.id;if(route.page==='tables'&&route.id!==null)S.tableId=Number(route.id);document.getElementById('sidebar').classList.remove('open');document.getElementById('menu-toggle').setAttribute('aria-expanded','false');render();window.scrollTo(0,0);document.getElementById('main').focus({preventScroll:true});}
function get(key){return key.split('.').reduce((o,k)=>o?.[k],S);}
function set(key,v){const path=key.split('.'),last=path.pop();let o=path.reduce((o,k)=>o[k],S);o[last]=v;}
function update(key,v){set(key,v);if(key==='caseId'){S.stage=0;S.cycleSummary=false;}if(key==='trace'){S.mutation=-1;S.traceStep=-1;}if(key==='mutation')S.traceStep=-1;
if(key==='tableId'){location.hash='/tables/'+v;return;}if(key==='dataTab'&&route.id){location.hash='/data/'+v;return;}if(key==='graphTab'&&route.id){location.hash='/graph/'+v;return;}if(key==='programTab'&&route.id){location.hash='/program/'+v;return;}
if(key==='formulaGroup'&&route.id){location.hash='/formulas';return;}if(key==='formulaSearch'&&route.page==='formulas'&&route.id){route.id=null;history.replaceState(null,'','#/formulas');}if(key==='glossarySearch'&&route.page==='glossary'&&route.id){route.id=null;history.replaceState(null,'','#/glossary');}render(true);}
function handleInput(event){const el=event.target,key=el.dataset.bind;if(!key)return;if(el.tagName==='SELECT'&&event.type==='input')return;if(el.type==='range'&&event.type==='change')return;if(['number','checkbox'].includes(el.type)&&event.type==='input')return;if(el.type==='search'&&event.type==='change')return;
let v;if(el.type==='checkbox')v=el.checked;else if(el.type==='number'||el.type==='range'||typeof get(key)==='number'){v=M.number(el.value);if(!Number.isFinite(v)){el.setCustomValidity('Введите допустимое число');el.reportValidity();return;}const min=el.getAttribute('min'),max=el.getAttribute('max');if(min!==null&&v<+min||max!==null&&v>+max){el.setCustomValidity('Число вне указанного диапазона');el.reportValidity();return;}el.setCustomValidity('');}else v=el.value;update(key,v);}
function shufflePermutations(a){if(a.length<2)return[a];return a.flatMap((x,i)=>shufflePermutations(a.filter((_,j)=>j!==i)).map(p=>[x,...p]));}
function setFeedback(id,type,title,text){S.feedback[id]={type,title,text};render(true);announce(title+' '+text);document.querySelector('.feedback')?.scrollIntoView({block:'nearest',behavior:'instant'});}
function handleAction(event){const b=event.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(b.tagName==='INPUT'&&event.type==='click'&&['toggle-measure','change-measure'].includes(a)){}else if(event.type!=='click')return;
if(a==='set'){const key=b.dataset.key,value=b.dataset.value;update(key,typeof get(key)==='number'?Number(value):value);return;}
if(a==='answer'){S.answers[b.dataset.question]=+b.dataset.index;delete S.feedback[b.dataset.question];b.dataset.focusKey='answer-'+b.dataset.question+'-'+b.dataset.index;render();document.querySelector(`[data-question="${CSS.escape(b.dataset.question)}"][data-index="${b.dataset.index}"]`)?.focus({preventScroll:true});return;}
if(a==='check'){const id=b.dataset.question,q=questions[id];if(S.answers[id]===undefined){setFeedback(id,'hint','Сначала выберите ответ','Нажмите на один из вариантов.');return;}const correct=S.answers[id]===q.correct;if(correct){S.mastery[id]=S.assisted[id]?'assisted':'independent';setFeedback(id,'success',S.assisted[id]?'Разобрано с помощью':'Верно · самостоятельно',q.feedback);}else{delete S.mastery[id];S.assisted[id]=true;setFeedback(id,'error','Разберём ошибку · следующая попытка с помощью',q.feedback);}return;}
if(a==='hint'){const id=b.dataset.question,q=questions[id];S.assisted[id]=true;S.mastery[id]='assisted';setFeedback(id,'hint','Объяснение · с помощью',q.options[q.correct]+'. '+q.feedback);return;}
if(a==='stage-prev'){S.stage=Math.max(0,S.stage-1);render();return;}if(a==='stage-next'){if(S.stage===11)S.cycleSummary=true;else S.stage++;render();return;}
if(a==='toggle-measure'){const id=b.value;S.selectedMeasures=b.checked?[...new Set([...S.selectedMeasures,id])]:S.selectedMeasures.filter(x=>x!==id);render();document.querySelector(`input[data-action="toggle-measure"][value="${id}"]`)?.focus({preventScroll:true});return;}
if(a==='change-measure'){const id=b.value;S.changedMeasures=b.checked?[...new Set([...S.changedMeasures,id])]:S.changedMeasures.filter(x=>x!==id);render();return;}
if(a==='add-measure'){const id=b.dataset.id;S.selectedMeasures=S.selectedMeasures.includes(id)?S.selectedMeasures.filter(x=>x!==id):[...S.selectedMeasures,id];render();return;}
if(a==='calendar-fix'){S.calendar={start1:1,duration1:5,load1:1,start2:6,duration2:2,load2:1,capacity:1};render();return;}if(a==='reset-calendar'){S.calendar=initialState().calendar;render();return;}
if(a==='reset-forecast'){Object.assign(S,{release:2025,horizon:3,model:'RT',kappa:5,floorFactor:1});render();return;}
if(a==='reset-economy'){S.p=.4;S.criterion='expected';S.limits=initialState().limits;render();return;}
if(a==='reset-info'){Object.assign(S,{p:.4,sensitivity:.8,specificity:.8,infoPrice:2,infoLabor:2,infoDelay:0});S.limits=initialState().limits;render();return;}
if(a==='trace-first'){S.traceStep=0;render();return;}if(a==='trace-step'){const arr=S.mutation>=0?M.mutateTrace(S.mutation):M.traceScenario(S.trace);S.traceStep=S.traceStep<0?1:Math.min(arr.length,S.traceStep+1);render();return;}if(a==='trace-all'){S.traceStep=-1;render();return;}
if(a==='permutations'){const base=M.traceBase();let total=0,accepted=0;for(const p of shufflePermutations(base)){total++;const rows=p.map((e,i)=>({...e,time:i}));if(M.validateTrace(rows).complete)accepted++;}S.permutationResult={total,accepted};render();announce(`Проверено ${total}, принято ${accepted}`);return;}
if(a==='graph-next'){S.graph.step=Math.min(12,S.graph.step+1);render();return;}if(a==='reset-graph'){S.graph=initialState().graph;render();return;}
if(a==='reset-mixture'){for(const k of['expertMedian','expertVariance','lambda','mixScale','compatible','mixThreshold','decisionThreshold'])S[k]=initialState()[k];render();return;}
if(a==='close-search'){document.getElementById('search-dialog').close();return;}if(a==='close-term'){document.getElementById('term-dialog').close();return;}
if(a==='term'){showTerm(b.dataset.term);return;}
if(a==='reset-session'){if(confirm('Очистить настройки и ответы текущего сеанса?')){S=initialState();location.hash='/home';route=parseRoute();render();announce('Сеанс очищен.');}return;}
if(a==='export-series'){const s=D.series.find(s=>s.id===S.indicator);U.downloadCSV('Наблюдаемый_ряд_'+s.id+'.csv',['Выпуск','Значение','Единица','Определение','Основание'],s.years.map((y,i)=>[y,s.values[i],s.unit,s.definition,s.source+'; фиксированная редакция']));return;}
if(a==='export-em'){const rows=D.em.filter(r=>r.indicator.replace('Х','X')===S.emIndicator);U.downloadCSV('Условные_траектории_'+S.emIndicator+'.csv',['Показатель','Вариант','Метка года','Значение','Статус'],rows.map(r=>[r.indicator,r.scenario,r.year,+r.value,'E/M: не наблюдение']));return;}
if(a==='export-forecast'){const rows=M.forecastAll(D.series,S.release,S.horizon,S.kappa,S.floorFactor);U.downloadCSV('Прогнозы_кампуса.csv',['Показатель','Модель','Выпуск начала','Горизонт','Медиана','Нижняя граница 95%','Верхняя граница 95%','Центр в z','Дисперсия в z','Условия'],rows.map(r=>[r.id,r.model,r.release,r.h,r.median,r.lo,r.hi,r.mu,r.V,`κ=${S.kappa}; множитель масштаба=${S.floorFactor}; фиксированный срез` ]));return;}
if(a==='export-economics'){const e=M.economy(D.economics,S.limits,S.p);U.downloadCSV('Условный_экономический_выбор.csv',['Вариант','Допущен','Причина','Ожидаемые полные затраты','Наихудшие полные затраты','p','Деньги','Труд','Срок','Повторяемость'],e.map(a=>[a.id,a.ok?'Да':'Нет',a.errors.join('; '),a.expected,a.worst,S.p,S.limits.cash,S.limits.labor,S.limits.hours,S.limits.repeat]));return;}
if(a==='export-table'){const t=D.tables.find(t=>t.index===+b.dataset.id);U.downloadCSV('Таблица_исследования_'+t.index+'.csv',t.rows[0],t.rows.slice(1));return;}
if(a==='export-trace'){const trace=S.mutation>=0?M.mutateTrace(S.mutation):M.traceScenario(S.trace);U.download('Учебная_трасса.json',JSON.stringify({origin:'Учебная трасса платформы; не производственный журнал',trace,result:M.validateTrace(trace)},null,2),'application/json');return;}
if(a==='export-program'){U.download('Учебная_конфигурация.json',JSON.stringify({origin:'Учебный выбор мер по авторским паспортам',selected:S.selectedMeasures,goal:S.goal,assumptions:S.existing,sameRoom:S.sameRoom,status:'Фактический ресурсный допуск не установлен: численные нагрузки и бюджеты отсутствуют в исходных паспортах'},null,2),'application/json');return;}
}
function showTerm(term){const t=V.allTerms().find(t=>t.term.toLowerCase()===term.toLowerCase())||V.allTerms().find(t=>t.term.toLowerCase().includes(term.toLowerCase()));document.getElementById('term-content').innerHTML=t?`<h2>${U.esc(t.term)}</h2><p>${U.esc(t.definition)}</p>${t.example?U.note(U.esc(t.example)):''}${t.quoteKey?U.quote(t.quoteKey,t.source):''}`:`<h2>${U.esc(term)}</h2><p>Найдите близкое понятие в полном глоссарии.</p>${U.link('Открыть глоссарий','#/glossary')}`;document.getElementById('term-dialog').showModal();}
const searchIndex=[...C.chapters.map(x=>({title:x.title,text:x.lead,kind:'Раздел '+x.id,url:'#/read/'+x.id})),...C.basics.map(x=>({title:x.title,text:x.explanation,kind:'Математическая основа',url:'#/basics/'+x.id})),...D.measures.map(x=>({title:x.id+' · '+x.title,text:x.purpose,kind:'Паспорт меры',url:'#/measure/'+x.id})),...D.formulas.map(x=>({title:'('+x.id+') '+x.title,text:x.explanation.join(' '),kind:'Формула',url:'#/formulas/'+x.id})),...V.allTerms().map(x=>({title:x.term,text:x.definition,kind:'Понятие',url:'#/glossary/'+encodeURIComponent(x.term)})),...D.series.map(x=>({title:x.id+' · '+x.short,text:x.definition,kind:'Официальный ряд',url:'#/data',indicator:x.id}))];
function search(query){const q=query.toLocaleLowerCase('ru').trim(),r=q?searchIndex.filter(x=>(x.title+' '+x.text).toLocaleLowerCase('ru').includes(q)).slice(0,35):searchIndex.slice(0,9);document.getElementById('search-results').innerHTML=r.map(x=>`<a class="search-row" href="${x.url}" ${x.indicator?`data-indicator="${x.indicator}"`:''}>${U.esc(x.title)}<small>${U.esc(x.kind)} · ${U.esc(x.text.slice(0,140))}</small></a>`).join('')||'<p class="no-results">Совпадений нет. Попробуйте другое слово.</p>';}
function openSearch(){document.getElementById('search-dialog').showModal();const i=document.getElementById('global-search');search(i.value);i.focus();}
document.addEventListener('input',handleInput);document.addEventListener('change',handleInput);document.addEventListener('click',handleAction);
document.addEventListener('click',event=>{const l=event.target.closest('a[href^="#/"]');if(!l)return;if(l.dataset.indicator){S.indicator=l.dataset.indicator;S.dataTab='official';}document.getElementById('search-dialog').close();document.getElementById('term-dialog').close();if(l.getAttribute('href')===location.hash)onRoute();});
document.getElementById('menu-toggle').innerHTML=g.icon('menu');document.getElementById('menu-toggle').addEventListener('click',()=>{const open=document.getElementById('sidebar').classList.toggle('open');document.getElementById('menu-toggle').setAttribute('aria-expanded',open);});document.getElementById('simple-mode').addEventListener('change',e=>{simple=e.target.checked;document.body.classList.toggle('simple',simple);});
document.getElementById('search-toggle').addEventListener('click',openSearch);document.getElementById('global-search').addEventListener('input',e=>search(e.target.value));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='/'){e.preventDefault();openSearch();}if(e.key==='Escape'){document.getElementById('sidebar').classList.remove('open');document.getElementById('menu-toggle').setAttribute('aria-expanded','false');}});
window.addEventListener('hashchange',onRoute);let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>render(true),180);});
g.CampusApp={get state(){return S;},questions,render,route:()=>route,searchIndex};onRoute();
})(window);
