/* Pure functions. Published examples and pedagogical models remain separate. */
(function(g){'use strict';
const sum=a=>a.reduce((s,x)=>s+x,0),mean=a=>a.length?sum(a)/a.length:NaN;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function number(s){s=String(s).trim().replace(/\s/g,'').replace(/−/g,'-').replace(/,/g,'.');if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)\/[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)){let[a,b]=s.split('/').map(Number);return b===0?NaN:a/b;}return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(s)&&Number.isFinite(+s)?+s:NaN;}
const near=(a,b,tol=1e-8)=>Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=tol*Math.max(1,Math.abs(b));
function inverse(A){const n=A.length;if(!n||A.some(r=>r.length!==n))throw Error('Матрица должна быть квадратной');let b=A.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]);for(let i=0;i<n;i++){let p=i;for(let k=i+1;k<n;k++)if(Math.abs(b[k][i])>Math.abs(b[p][i]))p=k;if(Math.abs(b[p][i])<1e-13)throw Error('Матрица вырождена');[b[i],b[p]]=[b[p],b[i]];let q=b[i][i];b[i]=b[i].map(x=>x/q);for(let k=0;k<n;k++)if(k!==i){let c=b[k][i];for(let j=0;j<2*n;j++)b[k][j]-=c*b[i][j];}}return b.map(r=>r.slice(n));}
const dot=(a,b)=>{if(a.length!==b.length)throw Error('Размеры не совпадают');return sum(a.map((x,i)=>x*b[i]));};
const matvec=(A,x)=>A.map(r=>dot(r,x));
function cdf(x){if(x===Infinity)return 1;if(x===-Infinity)return 0;const z=Math.abs(x)/Math.sqrt(2),t=1/(1+.3275911*z);const e=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-z*z);return .5*(1+(x<0?-e:e));}
const pdf=x=>Math.exp(-x*x/2)/Math.sqrt(2*Math.PI);
function crps(mu,V,y){if(V<=0)return Math.abs(y-mu);const s=Math.sqrt(V),u=(y-mu)/s;return s*(u*(2*cdf(u)-1)+2*pdf(u)-1/Math.sqrt(Math.PI));}
function transform(x,type){if(!Number.isFinite(x))throw Error('Нет допустимого значения');if(type==='log'){if(x<=0)throw Error('Для логарифма нужно положительное значение');return Math.log(x);}if(type==='logit'){if(x<0||x>100)throw Error('Доля должна лежать от 0 до 100%');let p=clamp(x/100,.005,.995);return Math.log(p/(1-p));}return x;}
function untransform(z,type){return type==='log'?Math.exp(z):type==='logit'?100/(1+Math.exp(-z)):z;}
function prepare(series,release,floorFactor=1){return series.map(s=>{const rows=s.values.map((v,i)=>({v,t:s.years[i]})).filter(r=>r.v!==null&&r.t<=release);if(rows.length<2)throw Error('Не хватает двух уровней истории');const z=rows.map(r=>transform(r.v,s.transform)),d=z.slice(1).map((v,i)=>v-z[i]),floor=(s.transform==='log'?.04:s.transform==='logit'?.20:2)*floorFactor;return{...s,rows,z,d,n:d.length,s:Math.max(mean(d.map(Math.abs)),floor),q:Math.sqrt(Math.max(mean(d.map(v=>v*v)),floor*floor)),floor};});}
function forecastAll(series,release=2025,h=3,kappa=5,floorFactor=1){const a=prepare(series,release,floorFactor),n=a.length,N=4+n,J=Array.from({length:N},(_,i)=>Array.from({length:N},(_,j)=>i===j?(i<4?2:10):0)),rhs=Array(N).fill(0);a.forEach((v,i)=>{let k=4+i,w=(v.s/v.q)**2;for(const d of v.d){const y=d/v.s;for(const r of [v.group,k]){rhs[r]+=w*y;for(const c of[v.group,k])J[r][c]+=w;}}});const inv=inverse(J),beta=matvec(inv,rhs);let out=[];a.forEach((v,i)=>{for(const model of['RW','RT','PP']){let drift=0,dv=0;if(model==='RT'){drift=sum(v.d)/(v.n+kappa);dv=v.q*v.q/(v.n+kappa);}if(model==='PP'){drift=v.s*(beta[v.group]+beta[4+i]);dv=v.s*v.s*(inv[v.group][v.group]+2*inv[v.group][4+i]+inv[4+i][4+i]);}let mu=v.z.at(-1)+h*drift,V=h*v.q*v.q+h*h*dv,sigma=Math.sqrt(V);out.push({id:v.id,model,release,h,mu,V,drift,driftVariance:dv,median:untransform(mu,v.transform),lo:untransform(mu-1.95996398454*sigma,v.transform),hi:untransform(mu+1.95996398454*sigma,v.transform),lo80:untransform(mu-1.281551565545*sigma,v.transform),hi80:untransform(mu+1.281551565545*sigma,v.transform),pBelowLast:cdf((v.z.at(-1)-mu)/sigma),history:v,groupPart:beta[v.group],individualPart:beta[4+i]});}});return out;}
function backtest(series){let rows=[];for(const release of[2023,2024]){for(const f of forecastAll(series,release,1)){const s=series.find(s=>s.id===f.id),y=s.values[s.years.indexOf(release+1)],z=transform(y,s.transform),error=f.mu-z;rows.push({...f,actual:y,zActual:z,ae:Math.abs(error)/f.history.s,se:(error/f.history.q)**2,crps:crps(f.mu,f.V,z)/f.history.s,cover80:y>=f.lo80&&y<=f.hi80,cover95:y>=f.lo&&y<=f.hi,width:(2*1.95996398454*Math.sqrt(f.V))/f.history.s});}}
return{rows,summary:['RW','RT','PP'].map(model=>{const r=rows.filter(x=>x.model===model);return{model,n:r.length,mase:mean(r.map(x=>x.ae)),rmsse:Math.sqrt(mean(r.map(x=>x.se))),crps:mean(r.map(x=>x.crps)),coverage80:mean(r.map(x=>+x.cover80))*100,coverage95:mean(r.map(x=>+x.cover95))*100,width:mean(r.map(x=>x.width))};})};}
const total=s=>s.direct+s.coord+s.loss;
function eligibility(alt,limits,extra={cash:0,labor:0,delay:0}){let errors=[];if(!alt.acceptance)errors.push('Нет независимой приёмки');if(alt.scenarios.some(s=>s.hours+(extra.delay||0)>limits.hours+1e-10))errors.push('Превышен срок');if(alt.scenarios.some(s=>s.repeat>limits.repeat+1e-10))errors.push('Превышена повторяемость');if(alt.scenarios.some(s=>s.direct+s.coord+(extra.cash||0)>limits.cash+1e-10))errors.push('Недостаточно денежных средств');if(alt.scenarios.some(s=>s.labor+(extra.labor||0)>limits.labor+1e-10))errors.push('Недостаточно рабочего времени');return{ok:!errors.length,errors};}
function economy(alts,limits,p){return alts.map(a=>({...a,...eligibility(a,limits),costs:a.scenarios.map(total),cash:Math.max(...a.scenarios.map(s=>s.direct+s.coord)),labor:Math.max(...a.scenarios.map(s=>s.labor)),expected:(1-p)*total(a.scenarios[0])+p*total(a.scenarios[1]),worst:Math.max(...a.scenarios.map(total))}));}
function choose(alts,p){if(!alts.length)return{cost:Infinity,ids:[]};const costs=alts.map(a=>({id:a.id,cost:(1-p)*total(a.scenarios[0])+p*total(a.scenarios[1])}));const m=Math.min(...costs.map(a=>a.cost));return{cost:m,ids:costs.filter(a=>near(a.cost,m)).map(a=>a.id)};}
function information(alts,limits,p,sensitivity=.8,specificity=.8,price=2,labor=2,delay=0){const base=alts.filter(a=>eligibility(a,limits).ok),withInfo=alts.filter(a=>eligibility(a,limits,{cash:price,labor,delay}).ok);if(!base.length||!withInfo.length)return{ok:false,reason:!base.length?'Нет допустимого фиксированного варианта':'Диагностика не оставляет допустимого исполнения'};const prior=choose(base,p);const high=p*sensitivity+(1-p)*(1-specificity),low=1-high,ph=high>1e-14?p*sensitivity/high:null,pl=low>1e-14?p*(1-sensitivity)/low:null;const ah=ph===null?{cost:0,ids:[]}:choose(withInfo,ph),al=pl===null?{cost:0,ids:[]}:choose(withInfo,pl);const conditional=high*ah.cost+low*al.cost,perfect=(1-p)*choose(base,0).cost+p*choose(base,1).cost;return{ok:true,prior,high,low,ph,pl,ah,al,conditional,price,cost:conditional+price,gross:prior.cost-conditional,net:prior.cost-conditional-price,perfect:prior.cost-perfect,restricted:withInfo.length!==base.length};}
function regret(alts,limits,pL,pU){const a=alts.filter(a=>eligibility(a,limits).ok);return a.map(v=>({id:v.id,worst:Math.max(...[pL,pU].map(p=>(1-p)*total(v.scenarios[0])+p*total(v.scenarios[1])-choose(a,p).cost))}));}
function expertWeight(V,Q,delta,lambda=.35,c=2.5,compatible=true){if(!compatible||V===0)return 0;return lambda*V/(V+Q+delta*delta/(c*c));}
function mixture(mu,V,e,Q,w){return{mean:(1-w)*mu+w*e,variance:(1-w)*V+w*Q+w*(1-w)*(e-mu)**2};}
function mixCDF(x,mu,V,e,Q,w){const F=(x,m,v)=>v===0?(x>=m?1:0):cdf((x-m)/Math.sqrt(v));return(1-w)*F(x,mu,V)+w*F(x,e,Q);}
function mixQuantile(p,mu,V,e,Q,w){let lo=Math.min(mu-12*Math.sqrt(V),e-12*Math.sqrt(Q))-1,hi=Math.max(mu+12*Math.sqrt(V),e+12*Math.sqrt(Q))+1;for(let i=0;i<90;i++){let m=(lo+hi)/2;if(mixCDF(m,mu,V,e,Q,w)<p)lo=m;else hi=m;}return hi;}
function intervalLoads(jobs,capacity){if(jobs.some(j=>!Number.isFinite(j.start)||!Number.isFinite(j.end)||j.end<=j.start||j.load<0))throw Error('Недопустимый интервал или нагрузка');const events=[...new Set(jobs.flatMap(j=>[j.start,j.end]))].sort((a,b)=>a-b);const seg=events.slice(0,-1).map((start,i)=>({start,end:events[i+1],load:sum(jobs.filter(j=>j.start<=start&&start<j.end).map(j=>j.load))}));return{segments:seg,conflicts:seg.filter(s=>s.load>capacity+1e-10),peak:Math.max(0,...seg.map(s=>s.load)),ok:seg.every(s=>s.load<=capacity+1e-10)};}
function affectedChecks(checks,changed,external=[],isComplete=true){if(!isComplete)return checks.map(r=>({...r,affected:true,why:'Полнота реестра не подтверждена: расширенная проверка'}));return checks.map(r=>({...r,affected:r.new||r.args.some(a=>[...changed,...external].includes(a)),why:r.new?'Новое ограничение':r.args.some(a=>[...changed,...external].includes(a))?'Изменилось основание':'Основание сохранено'}));}
function lagSimulation(edges,size,source,steps=12,amplitude=1){let states=[Array.from({length:size},(_,i)=>i===source?amplitude:0)];for(let t=0;t<steps;t++){let next=Array(size).fill(0);for(let e of edges){if(e.lag<0||!Number.isInteger(e.lag)||!Number.isFinite(e.weight))throw Error('Неверная связь');const past=states[t-e.lag];if(past)next[e.to]+=e.weight*past[e.from];}states.push(next);}return states;}
function companion(edges,n){const lag=Math.max(0,...edges.map(e=>e.lag)),N=n*(lag+1),A=Array.from({length:N},()=>Array(N).fill(0));for(const e of edges)A[e.to][e.from+e.lag*n]+=e.weight;for(let i=n;i<N;i++)A[i][i-n]=1;return A;}
function certify(edges,n,factor=1.2){const A=companion(edges,n),B=A.map((r,i)=>r.map(x=>Math.abs(x)*(i<n?factor:1)));try{const v=matvec(inverse(B.map((r,i)=>r.map((x,j)=>(i===j?1:0)-x))),Array(B.length).fill(1));const bv=matvec(B,v),q=Math.max(...bv.map((x,i)=>x/v[i]));return{A,B,v,bv,q,ok:v.every(x=>x>0)&&q>=0&&q<1,slack:bv.map((x,i)=>q*v[i]-x)};}catch(e){return{A,B,ok:false,error:e.message};}}
const actors={dispatcher:['register','cancel','reopen','close'],analyst:['diagnose','knowledge'],manager:['authorize','knowledge'],engineer:['execute'],engineer2:['execute'],inspector:['verify'],inspector2:['verify']};
function traceBase(){return[{id:'S1',caseId:'C-01',time:0,action:'register',actor:'dispatcher',rule:'v1'},{id:'S2',caseId:'C-01',time:1,action:'diagnose',actor:'analyst',rule:'v1',diagnosisId:'D1'},{id:'S3',caseId:'C-01',time:2,action:'authorize',actor:'manager',rule:'v1',diagnosisRef:'D1',decisionId:'R1',resourceConfirmed:true,limit:80},{id:'S4',caseId:'C-01',time:3,action:'execute',actor:'engineer',rule:'v1',decisionRef:'R1',executionId:'E1',labor:20},{id:'S5',caseId:'C-01',time:4,action:'verify',actor:'inspector',rule:'v1',executionRef:'E1',confirmed:true},{id:'S6',caseId:'C-01',time:5,action:'close',actor:'dispatcher',rule:'v1'}];}
function traceScenario(name){const a=traceBase();if(name==='normal')return a;if(name==='prefix')return a.slice(0,4);if(name==='cancel')return[a[0],{id:'S2',caseId:'C-01',time:1,action:'cancel',actor:'dispatcher',rule:'v1',reason:'Дублирующий случай; ссылка на основную заявку'}];if(name==='rework'||name==='old')return[...a.slice(0,5),{...a[3],id:'S7',time:5,executionId:'E2'},...(name==='rework'?[{...a[4],id:'S8',time:6,executionRef:'E2'}]:[]),{...a[5],id:'S9',time:7}];if(name==='self'){a[4].actor='engineer';return a;}if(name==='newdiagnosis')return[...a.slice(0,4),{...a[1],id:'S7',time:4,diagnosisId:'D2'},{...a[3],id:'S8',time:5,executionId:'E2'}];if(name==='reopen')return[...a,{...a[0],id:'S7',time:6,action:'reopen'},...a.slice(1).map((e,i)=>({...e,id:'N'+i,time:7+i,diagnosisId:e.diagnosisId?'D2':undefined,diagnosisRef:e.diagnosisRef?'D2':undefined,decisionId:e.decisionId?'R2':undefined,decisionRef:e.decisionRef?'R2':undefined,executionId:e.executionId?'E2':undefined,executionRef:e.executionRef?'E2':undefined}))];return a;}
function validateTrace(events){let ids=new Set(),execIds=new Set(),cycleActors=new Set(),currentCase=null,lastTime=-Infinity,registered=false,closed=false,cancelled=false,diag=null,decision=null,limit=0,used=0,execution=null,confirmed=false,log=[],cycle=1;const fail=(i,reason)=>({ok:false,complete:false,status:'Нарушение',index:i,reason,log,cycle});for(let i=0;i<events.length;i++){const e=events[i];if(!e.id||ids.has(e.id))return fail(i,'Идентификатор события отсутствует или повторяется');ids.add(e.id);if(!e.caseId||currentCase&&e.caseId!==currentCase)return fail(i,'Не указан единый управленческий случай');currentCase=e.caseId;if(!Number.isFinite(e.time))return fail(i,'Нет временной отметки');if(e.time<lastTime)return fail(i,'Нарушена исходная хронология');lastTime=e.time;if(e.rule!=='v1'||e.time>72)return fail(i,'Нет действующей версии правила');if(!actors[e.actor])return fail(i,'Участник отсутствует в справочнике полномочий');if(e.action==='verify'&&cycleActors.has(e.actor))return fail(i,'Приёмку проводит участник исполнения текущего цикла');if(!actors[e.actor].includes(e.action))return fail(i,'Нет полномочия на это действие');if(e.action==='register'){if(registered)return fail(i,'Повторная регистрация вместо нового цикла');registered=true;}
else if(!registered)return fail(i,'Сначала нужна регистрация случая');
else if(e.action==='reopen'){if(!closed&&!cancelled)return fail(i,'Повторно открывается только завершённый случай');closed=false;cancelled=false;diag=null;decision=null;execution=null;confirmed=false;cycleActors.clear();used=0;cycle++;}
else if(e.action==='knowledge'){if(!closed&&!cancelled)return fail(i,'Нет завершённого исхода для этого обновления');}
else if(closed||cancelled)return fail(i,'Случай завершён; требуется новый цикл');
else if(e.action==='diagnose'){if(!e.diagnosisId)return fail(i,'Не указан диагноз');diag=e.diagnosisId;decision=null;execution=null;confirmed=false;}
else if(e.action==='authorize'){if(!diag||e.diagnosisRef!==diag)return fail(i,'Нет ссылки на актуальный диагноз');if(e.resourceConfirmed!==true||!Number.isFinite(e.limit)||e.limit<0)return fail(i,'Ресурс не подтверждён');if(!e.decisionId)return fail(i,'Нет идентификатора решения');decision=e.decisionId;limit=e.limit;}
else if(e.action==='execute'){if(!decision||e.decisionRef!==decision)return fail(i,'Нет действующего разрешения на исполнение');if(!Number.isFinite(e.labor)||e.labor<0)return fail(i,'Недопустимая трудовая нагрузка');if(used+e.labor>limit+1e-10)return fail(i,'Превышен выделенный трудовой лимит текущего цикла');if(!e.executionId||execIds.has(e.executionId))return fail(i,'Исполнение должно иметь новый идентификатор');execIds.add(e.executionId);execution=e.executionId;cycleActors.add(e.actor);confirmed=false;used+=e.labor;}
else if(e.action==='verify'){if(!execution||e.executionRef!==execution)return fail(i,'Приёмка относится не к последнему исполнению');if(typeof e.confirmed!=='boolean')return fail(i,'Не указан результат проверки');confirmed=e.confirmed;}
else if(e.action==='close'){if(!execution||!confirmed)return fail(i,'Последнее исполнение не имеет положительной независимой приёмки');closed=true;}
else if(e.action==='cancel'){if(!e.reason)return fail(i,'Необходимо основание административного прекращения');cancelled=true;confirmed=false;}
else return fail(i,'Неизвестное действие');log.push({event:e.id,action:e.action,cycle,diagnosis:diag,decision,execution,confirmed,used,state:closed?'Закрыт с приёмкой':cancelled?'Прекращён без утверждения о восстановлении':'В работе'});}
return{ok:true,complete:closed,status:closed?'Подтверждённо завершён':cancelled?'Административно прекращён':'Допустимый незавершённый маршрут',reason:closed?'Последняя работа независимо проверена':cancelled?'Прекращение не означает восстановление сервиса':'Продолжение ещё требуется',log,cycle};}
function mutateTrace(index){let a=traceBase();switch(index){case 0:a[2].id=a[1].id;break;case 1:delete a[2].caseId;break;case 2:delete a[2].time;break;case 3:a[3].time=.5;break;case 4:[a[1],a[2]]=[a[2],a[1]];a.forEach((x,i)=>x.time=i);break;case 5:delete a[2].rule;break;case 6:a[2].time=73;break;case 7:a[2].actor='unknown';break;case 8:a[4].actor='engineer';break;case 9:a[4].executionRef='E0';break;case 10:a.splice(4,1);break;case 11:a[4].confirmed=false;break;case 12:a[3].labor=-1;break;case 13:a[3].labor=81;break;case 14:delete a[2].diagnosisRef;break;case 15:a[2].resourceConfirmed=false;break;}return a;}
function decompose(gaps){const m=mean(gaps),mse=mean(gaps.map(x=>x*x)),variance=mean(gaps.map(x=>(x-m)**2));return{mean:m,mse,aggregate:m*m,variance};}
function auditCosts(rows){let ids=new Set(),errors=[];rows.forEach(r=>{if(ids.has(r.id))errors.push('Дублирующаяся составляющая: '+r.id);ids.add(r.id);if(!near(sum(r.shares),1))errors.push('Доли не дают единицу: '+r.id);});return{ok:!errors.length,errors,total:sum(rows.map(r=>r.amount)),allocated:sum(rows.map(r=>r.amount*sum(r.shares)))};}
const api={sum,mean,clamp,number,near,dot,matvec,inverse,cdf,pdf,crps,transform,untransform,prepare,forecastAll,backtest,total,eligibility,economy,choose,information,regret,expertWeight,mixture,mixCDF,mixQuantile,intervalLoads,affectedChecks,lagSimulation,companion,certify,traceBase,traceScenario,validateTrace,mutateTrace,decompose,auditCosts};
g.CampusMath=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
