(function(g){'use strict';
const D=g.CAMPUS_DATA,M=g.CampusMath;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,n=2)=>x===null||x===undefined||!Number.isFinite(+x)?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:n}).format(+x);
const fixed=(x,n=3)=>new Intl.NumberFormat('ru-RU',{minimumFractionDigits:n,maximumFractionDigits:n}).format(x);
const statusNames={calculated:'Пересчёт по наблюдениям',O:'Наблюдаемые данные',EM:'Экспертно-модельные траектории',example:'Авторский условный расчёт',teaching:'Учебная иллюстрация',reported:'Опубликованный результат',project:'Проектная мера',alert:'Есть ограничение'};
const badge=(s,text)=>`<span class="badge ${s}">${esc(text||statusNames[s]||s)}</span>`;
const source=(t,table)=>`<span class="source">${table!==undefined?`<a href="#/tables/${table}">${esc(t)}</a>`:esc(t)}</span>`;
const btn=(label,action,data='',cls='')=>`<button class="btn ${cls}" data-action="${action}" ${data}>${label}</button>`;
const link=(label,href,cls='')=>`<a class="btn ${cls}" href="${href}">${label}</a>`;
function intro(title,description,origin,ref){return`<div class="intro"><h1>${title}</h1>${description?`<p>${description}</p>`:''}<div class="intro-meta">${origin?badge(origin):''}${ref?source(ref):''}</div></div>`;}
const teach=(text)=>`<div class="teach">${text}</div>`;
const note=(text,type='')=>`<div class="note ${type}">${text}</div>`;
const metric=(value,caption,negative=false)=>`<div class="metric ${negative?'negative':''}"><div class="value">${value}</div><div class="caption">${caption}</div></div>`;
function table(headers,rows,options={}){return`<div class="table-wrap" tabindex="0" role="region" aria-label="${esc(options.label||'Таблица данных')}"><table class="${options.wide?'wide-table':''}"><thead><tr>${headers.map((h,i)=>`<th scope="col" class="${options.numeric?.includes(i)?'numeric':''}">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr class="${options.highlights?.includes(i)?'selected':''}">${r.map((x,j)=>`<td class="${options.numeric?.includes(j)?'numeric':''}">${esc(x===null?'—':x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function input(key,label,value,min,max,step=1){return`<label class="control">${esc(label)}<input type="number" data-bind="${key}" value="${value}" min="${min}" max="${max}" step="${step}" inputmode="decimal"></label>`;}
function range(key,label,value,min,max,step=.01,format=2){return`<label class="control">${esc(label)} <output>${fmt(value,format)}</output><input type="range" data-bind="${key}" aria-label="${esc(label)}" value="${value}" min="${min}" max="${max}" step="${step}"></label>`;}
function select(key,label,value,options){return`<label class="control">${esc(label)}<select data-bind="${key}">${options.map(o=>{const v=Array.isArray(o)?o[0]:o,t=Array.isArray(o)?o[1]:o;return`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;}
const checkbox=(key,label,value)=>`<label class="check-line"><input type="checkbox" data-bind="${key}" ${value?'checked':''}><span>${label}</span></label>`;
const tabs=(key,value,options)=>`<div class="tabs" role="tablist">${options.map(([id,label])=>`<button role="tab" aria-selected="${value===id}" class="${value===id?'active':''}" data-action="set" data-key="${key}" data-value="${id}">${label}</button>`).join('')}</div>`;
function formulaGuide(id,expanded=false){const a=g.CAMPUS_FORMULA_GUIDES?.[id];if(!a)return '';return `<p class="formula-reading">${esc(a.reading)}</p><details ${expanded?'open':''}><summary>Что означает каждый символ</summary>${table(['Обозначение','Простыми словами'],a.symbols)}</details>${a.example?note(esc(a.example)):''}`;}
function formula(id,more=false){const f=D.formulas.find(f=>f.id===id);if(!f)return '';const html=`<div class="equation" role="region" aria-label="Формула ${id}" tabindex="0">${f.math.join('')}</div><div class="eq-meta"><span>Формула (${id})</span><a href="#/formulas/${id}" class="inline-link">Разобрать запись</a></div>`;return more?`<details><summary>Математическая запись · (${id})</summary>${html}<p>${f.explanation.map(esc).join(' ')}</p>${formulaGuide(id)}</details>`:html;}
function quote(key,ref){return D.quotes[key]?`<details><summary>Точная формулировка исследования</summary><blockquote>${esc(D.quotes[key])}</blockquote><div class="quote-source">${esc(ref)}</div></details>`:'';}
function lineChart(series,labels,options={}){const W=innerWidth<760?360:660,H=options.height||270,left=innerWidth<760?60:78,right=20,top=25,bottom=45;const finite=series.flatMap(s=>s.values).filter(v=>Number.isFinite(v)),extra=(options.bands||[]).flatMap(b=>[...b.low,...b.high]).filter(v=>Number.isFinite(v));const all=[...finite,...extra];if(!all.length)return note('Нет чисел для диаграммы.');let min=Math.min(...all),max=Math.max(...all),pad=(max-min)*.12||Math.max(1,Math.abs(max)*.08);min-=pad;max+=pad;if(options.zero&&min>0)min=0;const x=i=>left+i*(W-left-right)/Math.max(1,labels.length-1),y=v=>H-bottom-(v-min)/(max-min)*(H-bottom-top),color=['#2b6653','#b36b36','#476893'];let svg=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(options.title||'Динамика значений')}"><title>${esc(options.title||'Динамика значений')}</title><desc>Точные значения доступны в таблице под диаграммой. ${esc(options.desc||'')}</desc>`;for(let i=0;i<5;i++){let v=min+i*(max-min)/4,Y=y(v);svg+=`<line class="grid" x1="${left}" x2="${W-right}" y1="${Y}" y2="${Y}"/><text x="${left-9}" y="${Y+4}" text-anchor="end">${fmt(v,options.decimals??1)}</text>`;}labels.forEach((l,i)=>{if(labels.length<=8||i%2===0||i===labels.length-1)svg+=`<text x="${x(i)}" y="${H-15}" text-anchor="middle">${esc(l)}</text>`;});for(const b of options.bands||[]){const points=b.low.map((v,i)=>Number.isFinite(v)?[i,v]:null).filter(Boolean);const upper=b.high.map((v,i)=>Number.isFinite(v)?[i,v]:null).filter(Boolean).reverse();svg+=`<path d="${[...points,...upper].map(([i,v],k)=>(k?'L':'M')+x(i)+','+y(v)).join(' ')} Z" fill="#6c976d" opacity=".15"/>`;}
series.forEach((s,si)=>{let p='',last=false;s.values.forEach((v,i)=>{if(!Number.isFinite(v)){last=false;return;}p+=(last?'L':'M')+x(i)+','+y(v)+' ';last=true;});svg+=`<path class="series" d="${p}" stroke="${s.color||color[si%3]}" ${s.dash?'stroke-dasharray="7 5"':''}/>`;s.values.forEach((v,i)=>{if(Number.isFinite(v)&&s.values.length<15)svg+=`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="${s.color||color[si%3]}"><title>${esc(s.name)} · ${esc(labels[i])}: ${fmt(v,6)}</title></circle>`;});});if(options.divider!==undefined){svg+=`<line x1="${x(options.divider)}" x2="${x(options.divider)}" y1="${top}" y2="${H-bottom}" stroke="#97a79b" stroke-dasharray="3 5"/>`;}
svg+='</svg>';return`<div class="legend">${series.map((s,i)=>`<span><i style="background:${s.color||color[i%3]};${s.dash?'background:repeating-linear-gradient(90deg,'+(s.color||color[i%3])+' 0 5px,transparent 5px 8px)':''}"></i>${esc(s.name)}</span>`).join('')}</div>${svg}<div class="chart-caption">${esc(options.caption||'Вертикальная шкала адаптирована к диапазону значений. Сравнивайте подписи оси, не только наклон линии.')}</div>`;}
function bars(items,maxValue=null){const max=maxValue||Math.max(...items.map(x=>Math.abs(x.value)))||1;return items.map(i=>`<div class="a-row"><div style="min-width:105px;max-width:50%">${esc(i.label)}</div><div style="flex:1"><div class="bar-track"><div class="bar-fill" style="width:${clamp100(Math.abs(i.value)/max*100)}%;background:${i.color||'#2b6653'}"></div></div></div><b class="mono">${fmt(i.value,i.digits??3)}</b></div>`).join('');}
const clamp100=x=>Math.max(0,Math.min(100,x));
function question(q,id,session){const a=session.answers[id],status=session.feedback[id];return`<div class="task-block"><h3 class="task-title">${esc(q.prompt)}</h3><div class="options" role="group" aria-label="Варианты ответа">${q.options.map((o,i)=>`<button class="option ${a===i?'selected':''}" aria-pressed="${a===i}" data-action="answer" data-question="${id}" data-index="${i}"><span class="letter">${'АБВГД'[i]}</span>${esc(o)}</button>`).join('')}</div><div class="actions">${btn('Проверить','check',`data-question="${id}"`,'primary')}${btn('Объяснить','hint',`data-question="${id}"`,'small')}</div>${status?`<div class="feedback ${status.type}" role="status"><b>${esc(status.title)}</b>${esc(status.text)}</div>`:''}</div>`;}
function downloadCSV(name,headers,rows){const cell=v=>{const numeric=typeof v==='number'&&Number.isFinite(v);let s=numeric?String(v).replace('.',','):String(v??'');if(!numeric&&/^[=+@\-]/.test(s)&&!Number.isFinite(+s.replace(',','.')))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const csv='\ufeff'+[headers,...rows].map(r=>r.map(cell).join(';')).join('\r\n');download(name,csv,'text/csv;charset=utf-8');}
function download(name,data,type){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
g.CampusUI={esc,fmt,fixed,badge,source,btn,link,intro,teach,note,metric,table,input,range,select,checkbox,tabs,formula,formulaGuide,quote,lineChart,bars,question,downloadCSV,download};
})(window);
