/* Run with Node >= 18: node tests/math.test.cjs. No dependencies. */
'use strict';const assert=require('node:assert/strict');global.window={};require('../js/data.js');require('../js/content.js');require('../js/formula-guides.js');const D=window.CAMPUS_DATA,C=window.CAMPUS_CONTENT,M=require('../js/math.js');let count=0;const check=(x,msg)=>{count++;assert.ok(x,msg)};const near=(a,b,t=1e-8)=>check(M.near(a,b,t),`${a} != ${b}`);
check(D.series.length===16);check(D.series.reduce((n,s)=>n+s.values.filter(x=>x!==null).length,0)===69);check(D.em.length===420);check(D.nodes.length===35);check(D.measures.length===12);check(D.formulas.length===53);check(D.formulas.every(f=>f.math.length));for(const f of D.formulas){const n=window.CAMPUS_FORMULA_GUIDES[f.id];check(n&&n.reading.length>20&&n.symbols.length>1);check(n.symbols.every(r=>r.length===2&&r[0]&&r[1]));}check(D.formulas.find(f=>f.id==='2.6').math.length===3);check(new Set(D.formulas.map(f=>f.id)).size===53);
near(M.number(' 1/2 '),.5);near(M.number('−0,2'),-.2);check(Number.isNaN(M.number('')));check(Number.isNaN(M.number('1/0')));check(Number.isNaN(M.number('1+2')));
for(const s of D.series)for(const v of s.values)if(v!==null)near(M.untransform(M.transform(v,s.transform),s.transform),v);
const refs={RW:[.626,.838,.492,84.38,93.75,4.181],RT:[.605,.820,.486,87.50,93.75,4.479],PP:[.622,.881,.512,90.63,93.75,4.525]};const bt=M.backtest(D.series);check(bt.rows.length===96);for(const r of bt.summary){check(r.n===32);[r.mase,r.rmsse,r.crps,r.coverage80,r.coverage95,r.width].forEach((v,i)=>check(Math.abs(v-refs[r.model][i])<.0051));}
const ff=M.forecastAll(D.series);for(const f of ff){check(f.V>0);check(f.lo<=f.median&&f.median<=f.hi);check(f.history.n===3||f.history.n===4);}const area=ff.find(f=>f.id==='AREA_PC'&&f.model==='RT');near(area.median,15.356675294380203);near(area.lo,12.68422157325658);near(area.hi,18.59219146677839);
// Changing a held-out value must not change a forecast fitted before it.
let dd=JSON.parse(JSON.stringify(D.series));dd[0].values[4]*=9;const a=M.forecastAll(D.series,2024,1),b=M.forecastAll(dd,2024,1);a.forEach((f,i)=>{near(f.mu,b[i].mu);near(f.V,b[i].V)});
const lim={cash:180,labor:80,hours:48,repeat:.1};const econ=M.economy(D.economics,lim,.4);check(econ.filter(a=>a.ok).map(a=>a.id).join('')==='CE');near(econ.find(a=>a.id==='C').expected,134);near(econ.find(a=>a.id==='E').expected,136);check(M.choose(D.economics.filter(a=>M.eligibility(a,lim).ok),1/3).ids.length===2);check(!M.eligibility(D.economics[1],{cash:999,labor:999,hours:999,repeat:1}).ok);check(M.eligibility(D.economics[3],{...lim,labor:95}).ok);
let info=M.information(D.economics,lim,.4);near(info.high,.44);near(info.ph,8/11);near(info.pl,1/7);near(info.conditional,130.8);near(info.gross,3.2);near(info.net,1.2);near(info.cost,132.8);near(info.perfect,6);
for(let k=0;k<=1008;k++){const p=k/1008,r=M.information(D.economics,lim,p);check(r.ok);near(r.gross,Math.max(0,Math.min(18*p-2,8-12*p)),1e-8);check(r.gross>=-1e-8&&r.gross<=r.perfect+1e-8);}
for(const p of[0,.4,1])for(const se of[0,.8,1])for(const sp of[0,.8,1]){const r=M.information(D.economics,lim,p,se,sp);check(Number.isFinite(r.cost));near(r.high+r.low,1);}
check(!M.information(D.economics,{...lim,cash:0},.4).ok);check(!M.information(D.economics,lim,.4,.8,.8,2,100).ok);near(M.information(D.economics,lim,.4,.8,.8,4).net,-.8);
const baseJobs=[{start:1,end:6,load:1},{start:2,end:7,load:1}];check(!M.intervalLoads(baseJobs,1).ok);check(M.intervalLoads([{start:1,end:6,load:1},{start:6,end:8,load:1}],1).ok);
for(let start=0;start<4;start++)for(let dur=1;dur<4;dur++)for(let start2=0;start2<4;start2++)for(let dur2=1;dur2<4;dur2++){const j=[{start,end:start+dur,load:1},{start:start2,end:start2+dur2,load:1}],calc=M.intervalLoads(j,1),ref=Array.from({length:9},(_,t)=>j.filter(x=>x.start<=t&&t<x.end).length);check(calc.ok===ref.every(n=>n<=1));}
for(const name of['normal','rework','reopen'])check(M.validateTrace(M.traceScenario(name)).complete,name);for(const name of['old','self','newdiagnosis'])check(!M.validateTrace(M.traceScenario(name)).ok,name);check(M.validateTrace(M.traceScenario('prefix')).ok&&!M.validateTrace(M.traceScenario('prefix')).complete);check(M.validateTrace(M.traceScenario('cancel')).ok&&!M.validateTrace(M.traceScenario('cancel')).complete);for(let k=0;k<16;k++)check(!M.validateTrace(M.mutateTrace(k)).ok,'mutation '+k);
function perms(a){return a.length<2?[a]:a.flatMap((x,i)=>perms(a.filter((_,j)=>j!==i)).map(p=>[x,...p]));}let approved=0,total=0;for(const p of perms(M.traceBase())){total++;const r=M.validateTrace(p.map((e,i)=>({...e,time:i})));if(r.complete)approved++;check(!r.complete||r.ok)}check(total===720&&approved===1);
// Edge cases of the limited mixture, including zero statistical variance and invalid compatibility.
near(M.expertWeight(0,1,2),0);near(M.expertWeight(1,0,0,.35,2.5,false),0);
for(let i=0;i<200;i++){const V=(i%17+.1)/10,Q=(i%13)/10,d=(i-100)/15,l=.35,c=2.5,w=M.expertWeight(V,Q,d,l,c),r=M.mixture(0,V,d,Q,w);check(w>=0&&w<=l);check(Math.abs(r.mean)<=l*c*V/(2*Math.sqrt(V+Q))+1e-10);check(r.variance<=V*(1+l*Math.max(1,c*c))+1e-10);near(M.expertWeight(V*9,Q*9,d*3,l,c),w);const lo=M.mixQuantile(.025,0,V,d,Q,w),hi=M.mixQuantile(.975,0,V,d,Q,w);check(lo<=hi);check(M.mixCDF(lo,0,V,d,Q,w)>=.025-1e-7);}
const edges=[{from:0,to:1,weight:.3,lag:0},{from:1,to:2,weight:.4,lag:1},{from:2,to:0,weight:-.1,lag:1}],states=M.lagSimulation(edges,3,0,12);near(states[1][1],.3);near(states[2][2],0);near(states[3][2],.12);check(M.certify(edges,3).ok);const A=M.companion(edges,3);check(A.length===6);const dec=M.decompose([-2,2]);near(dec.mean,0);near(dec.mse,4);near(dec.mse,dec.aggregate+dec.variance);
check(M.auditCosts([{id:'x',amount:80,shares:[.25,.75]},{id:'y',amount:20,shares:[1]},{id:'z',amount:40,shares:[1]},{id:'r',amount:-10,shares:[1]}]).ok);near(M.auditCosts([{id:'x',amount:80,shares:[.25,.75]},{id:'y',amount:20,shares:[1]},{id:'z',amount:40,shares:[1]},{id:'r',amount:-10,shares:[1]}]).total,130);check(!M.auditCosts([{id:'x',amount:80,shares:[1.25]}]).ok);
const ac=M.affectedChecks(C.checks,['M05']);check(ac.find(c=>c.id==='labor').affected);check(!ac.find(c=>c.id==='room').affected);check(M.affectedChecks(C.checks,[],[],false).every(c=>c.affected));
for(const q of[...C.chapters.map(c=>c.question),...C.basics.map(b=>b.question),...C.cases.flatMap(c=>c.questions)]){check(q.options.length>=3);check(q.correct>=0&&q.correct<q.options.length);check(q.feedback.length>10);}
console.log(JSON.stringify({status:'passed',assertions:count,backtest:bt.summary,permutations:{total,approved}},null,2));
